#!/usr/bin/perl

# Copyright (c) 2016, Carsten Kunze <carsten.kunze@arcor.de>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

use warnings;
use strict;

our %labels;

print <<EOT;
\\makeatletter
\\def\\Ref#1{%
  {%
  {\\def\\\@XrefText{ref #1 }\\let\\next=\\\@XrefText\\\@MkXrefEnt}%
  \\def\\A{#1}%
EOT

while (<>) {
	/^ref (.+) (\d+)$/ and do {
		my $label = $1;
		my $pgNr  = $2;
		print <<EOT;
  \\def\\B{$label}\\ifx\\A\\B\\\@CurPgNr=$pgNr\\fi
EOT
		next;
	};
	/^label ([^\\]+)\\ nr ([^\\]+)\\ hdNr ([^\\]+)\\ hdTxt (.+)\\ (\d+)$/
	    or die "$0: Invalid syntax: $_";
	my $label = $1;
	my $nr    = $2;
	my $hdNr  = $3;
	my $hdTxt = $4;
	my $pgNr  = $5;
	$labels{$label} and die "$0: Label \"$label\" is already defined\n";
	print <<EOT;
  \\def\\B{$label}%
  \\ifx\\A\\B
    \\RefPgNr=$pgNr
    \\xdef\\RefNr{$nr}%
    \\xdef\\RefHdNr{$hdNr}%
    \\xdef\\RefHd{$hdTxt}%
  \\fi
EOT
}

print <<EOT;
  \\count255=\\\@CurPgNr\\advance\\count255 by1
  \\ifnum\\RefPgNr=\\count255
    \\xdef\\RefPg{ on the next page}%
  \\else
    \\count255=\\\@CurPgNr\\advance\\count255 by-1
    \\ifnum\\RefPgNr=\\count255
      \\xdef\\RefPg{ on the previous page}%
    \\else
      \\ifnum\\RefPgNr=\\\@CurPgNr
        \\xdef\\RefPg{}%
      \\else
        \\xdef\\RefPg{ on page~\\the\\RefPgNr}%
      \\fi
    \\fi
  \\fi
  }%
}%
\\makeatother
EOT
